// Contrato do canal painel ↔ agente (ARQUITETURA §7).
//
// Quem abre a conexão é SEMPRE o agente (só saída): Inscrever uma vez, com um token
// de uso único, para receber a identidade; depois Conectar num stream bidirecional
// sobre mTLS, por onde passam batimentos, tarefas, eventos e controles.
//
// Regras de entrega: pelo menos uma vez + idempotência. Toda tarefa tem `id`; todo
// evento tem `seq` crescente por tarefa; quem recebe ignora repetidos e confirma com
// `Confirmacao`. O agente guarda o que ainda não foi confirmado e reenvia ao voltar.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: revoada/agente/v1/agente.proto

package agentev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Canal_Inscrever_FullMethodName = "/revoada.agente.v1.Canal/Inscrever"
	Canal_Conectar_FullMethodName  = "/revoada.agente.v1.Canal/Conectar"
)

// CanalClient is the client API for Canal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CanalClient interface {
	// Inscrever troca o token de uso único por um certificado de cliente (mTLS), a CA
	// do painel e a chave pública que assina as tarefas. Só TLS (sem certificado de
	// cliente — o agente ainda não tem um); o agente confere a CA pela impressão
	// digital que vem dentro do token.
	Inscrever(ctx context.Context, in *PedidoInscricao, opts ...grpc.CallOption) (*RespostaInscricao, error)
	// Conectar é o canal de trabalho. Exige o certificado emitido na inscrição.
	Conectar(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MsgAgente, MsgPainel], error)
}

type canalClient struct {
	cc grpc.ClientConnInterface
}

func NewCanalClient(cc grpc.ClientConnInterface) CanalClient {
	return &canalClient{cc}
}

func (c *canalClient) Inscrever(ctx context.Context, in *PedidoInscricao, opts ...grpc.CallOption) (*RespostaInscricao, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespostaInscricao)
	err := c.cc.Invoke(ctx, Canal_Inscrever_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canalClient) Conectar(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MsgAgente, MsgPainel], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Canal_ServiceDesc.Streams[0], Canal_Conectar_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MsgAgente, MsgPainel]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Canal_ConectarClient = grpc.BidiStreamingClient[MsgAgente, MsgPainel]

// CanalServer is the server API for Canal service.
// All implementations must embed UnimplementedCanalServer
// for forward compatibility.
type CanalServer interface {
	// Inscrever troca o token de uso único por um certificado de cliente (mTLS), a CA
	// do painel e a chave pública que assina as tarefas. Só TLS (sem certificado de
	// cliente — o agente ainda não tem um); o agente confere a CA pela impressão
	// digital que vem dentro do token.
	Inscrever(context.Context, *PedidoInscricao) (*RespostaInscricao, error)
	// Conectar é o canal de trabalho. Exige o certificado emitido na inscrição.
	Conectar(grpc.BidiStreamingServer[MsgAgente, MsgPainel]) error
	mustEmbedUnimplementedCanalServer()
}

// UnimplementedCanalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCanalServer struct{}

func (UnimplementedCanalServer) Inscrever(context.Context, *PedidoInscricao) (*RespostaInscricao, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inscrever not implemented")
}
func (UnimplementedCanalServer) Conectar(grpc.BidiStreamingServer[MsgAgente, MsgPainel]) error {
	return status.Errorf(codes.Unimplemented, "method Conectar not implemented")
}
func (UnimplementedCanalServer) mustEmbedUnimplementedCanalServer() {}
func (UnimplementedCanalServer) testEmbeddedByValue()               {}

// UnsafeCanalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CanalServer will
// result in compilation errors.
type UnsafeCanalServer interface {
	mustEmbedUnimplementedCanalServer()
}

func RegisterCanalServer(s grpc.ServiceRegistrar, srv CanalServer) {
	// If the following call pancis, it indicates UnimplementedCanalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Canal_ServiceDesc, srv)
}

func _Canal_Inscrever_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PedidoInscricao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanalServer).Inscrever(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Canal_Inscrever_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanalServer).Inscrever(ctx, req.(*PedidoInscricao))
	}
	return interceptor(ctx, in, info, handler)
}

func _Canal_Conectar_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CanalServer).Conectar(&grpc.GenericServerStream[MsgAgente, MsgPainel]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Canal_ConectarServer = grpc.BidiStreamingServer[MsgAgente, MsgPainel]

// Canal_ServiceDesc is the grpc.ServiceDesc for Canal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Canal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "revoada.agente.v1.Canal",
	HandlerType: (*CanalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inscrever",
			Handler:    _Canal_Inscrever_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Conectar",
			Handler:       _Canal_Conectar_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "revoada/agente/v1/agente.proto",
}
