// Contrato do canal painel ↔ agente (ARQUITETURA §7).
//
// Quem abre a conexão é SEMPRE o agente (só saída): Inscrever uma vez, com um token
// de uso único, para receber a identidade; depois Conectar num stream bidirecional
// sobre mTLS, por onde passam batimentos, tarefas, eventos e controles.
//
// Regras de entrega: pelo menos uma vez + idempotência. Toda tarefa tem `id`; todo
// evento tem `seq` crescente por tarefa; quem recebe ignora repetidos e confirma com
// `Confirmacao`. O agente guarda o que ainda não foi confirmado e reenvia ao voltar.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: revoada/agente/v1/agente.proto

package agentev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventoTarefa_Nivel int32

const (
	EventoTarefa_INFO  EventoTarefa_Nivel = 0
	EventoTarefa_AVISO EventoTarefa_Nivel = 1
	EventoTarefa_ERRO  EventoTarefa_Nivel = 2
)

// Enum value maps for EventoTarefa_Nivel.
var (
	EventoTarefa_Nivel_name = map[int32]string{
		0: "INFO",
		1: "AVISO",
		2: "ERRO",
	}
	EventoTarefa_Nivel_value = map[string]int32{
		"INFO":  0,
		"AVISO": 1,
		"ERRO":  2,
	}
)

func (x EventoTarefa_Nivel) Enum() *EventoTarefa_Nivel {
	p := new(EventoTarefa_Nivel)
	*p = x
	return p
}

func (x EventoTarefa_Nivel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventoTarefa_Nivel) Descriptor() protoreflect.EnumDescriptor {
	return file_revoada_agente_v1_agente_proto_enumTypes[0].Descriptor()
}

func (EventoTarefa_Nivel) Type() protoreflect.EnumType {
	return &file_revoada_agente_v1_agente_proto_enumTypes[0]
}

func (x EventoTarefa_Nivel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventoTarefa_Nivel.Descriptor instead.
func (EventoTarefa_Nivel) EnumDescriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{6, 0}
}

type ResultadoTarefa_Estado int32

const (
	ResultadoTarefa_ESTADO_NENHUM ResultadoTarefa_Estado = 0
	ResultadoTarefa_SUCESSO       ResultadoTarefa_Estado = 1
	ResultadoTarefa_FALHA         ResultadoTarefa_Estado = 2
	ResultadoTarefa_CANCELADA     ResultadoTarefa_Estado = 3
	ResultadoTarefa_RECUSADA      ResultadoTarefa_Estado = 4 // assinatura inválida, tipo não liberado ou tarefa vencida
)

// Enum value maps for ResultadoTarefa_Estado.
var (
	ResultadoTarefa_Estado_name = map[int32]string{
		0: "ESTADO_NENHUM",
		1: "SUCESSO",
		2: "FALHA",
		3: "CANCELADA",
		4: "RECUSADA",
	}
	ResultadoTarefa_Estado_value = map[string]int32{
		"ESTADO_NENHUM": 0,
		"SUCESSO":       1,
		"FALHA":         2,
		"CANCELADA":     3,
		"RECUSADA":      4,
	}
)

func (x ResultadoTarefa_Estado) Enum() *ResultadoTarefa_Estado {
	p := new(ResultadoTarefa_Estado)
	*p = x
	return p
}

func (x ResultadoTarefa_Estado) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultadoTarefa_Estado) Descriptor() protoreflect.EnumDescriptor {
	return file_revoada_agente_v1_agente_proto_enumTypes[1].Descriptor()
}

func (ResultadoTarefa_Estado) Type() protoreflect.EnumType {
	return &file_revoada_agente_v1_agente_proto_enumTypes[1]
}

func (x ResultadoTarefa_Estado) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultadoTarefa_Estado.Descriptor instead.
func (ResultadoTarefa_Estado) EnumDescriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{8, 0}
}

type Controle_Acao int32

const (
	Controle_ACAO_NENHUMA Controle_Acao = 0
	Controle_PAUSAR       Controle_Acao = 1
	Controle_RETOMAR      Controle_Acao = 2
	Controle_CANCELAR     Controle_Acao = 3
)

// Enum value maps for Controle_Acao.
var (
	Controle_Acao_name = map[int32]string{
		0: "ACAO_NENHUMA",
		1: "PAUSAR",
		2: "RETOMAR",
		3: "CANCELAR",
	}
	Controle_Acao_value = map[string]int32{
		"ACAO_NENHUMA": 0,
		"PAUSAR":       1,
		"RETOMAR":      2,
		"CANCELAR":     3,
	}
)

func (x Controle_Acao) Enum() *Controle_Acao {
	p := new(Controle_Acao)
	*p = x
	return p
}

func (x Controle_Acao) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Controle_Acao) Descriptor() protoreflect.EnumDescriptor {
	return file_revoada_agente_v1_agente_proto_enumTypes[2].Descriptor()
}

func (Controle_Acao) Type() protoreflect.EnumType {
	return &file_revoada_agente_v1_agente_proto_enumTypes[2]
}

func (x Controle_Acao) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Controle_Acao.Descriptor instead.
func (Controle_Acao) EnumDescriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{15, 0}
}

type PedidoInscricao struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CsrDer        []byte                 `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`          // pedido de certificado (chave ECDSA P-256 gerada no agente)
	ChaveSelo     []byte                 `protobuf:"bytes,3,opt,name=chave_selo,json=chaveSelo,proto3" json:"chave_selo,omitempty"` // chave pública X25519: o painel sela credenciais para ela
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	So            string                 `protobuf:"bytes,5,opt,name=so,proto3" json:"so,omitempty"`     // linux | windows | darwin
	Arch          string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"` // amd64 | arm64
	Versao        string                 `protobuf:"bytes,7,opt,name=versao,proto3" json:"versao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PedidoInscricao) Reset() {
	*x = PedidoInscricao{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PedidoInscricao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedidoInscricao) ProtoMessage() {}

func (x *PedidoInscricao) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedidoInscricao.ProtoReflect.Descriptor instead.
func (*PedidoInscricao) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{0}
}

func (x *PedidoInscricao) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PedidoInscricao) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *PedidoInscricao) GetChaveSelo() []byte {
	if x != nil {
		return x.ChaveSelo
	}
	return nil
}

func (x *PedidoInscricao) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PedidoInscricao) GetSo() string {
	if x != nil {
		return x.So
	}
	return ""
}

func (x *PedidoInscricao) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *PedidoInscricao) GetVersao() string {
	if x != nil {
		return x.Versao
	}
	return ""
}

type RespostaInscricao struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AgenteId              string                 `protobuf:"bytes,1,opt,name=agente_id,json=agenteId,proto3" json:"agente_id,omitempty"`
	CertificadoDer        []byte                 `protobuf:"bytes,2,opt,name=certificado_der,json=certificadoDer,proto3" json:"certificado_der,omitempty"`
	CaDer                 []byte                 `protobuf:"bytes,3,opt,name=ca_der,json=caDer,proto3" json:"ca_der,omitempty"`
	ChaveAssinaturaPainel []byte                 `protobuf:"bytes,4,opt,name=chave_assinatura_painel,json=chaveAssinaturaPainel,proto3" json:"chave_assinatura_painel,omitempty"` // Ed25519: o agente só executa tarefa assinada por ela
	ValidoAte             int64                  `protobuf:"varint,5,opt,name=valido_ate,json=validoAte,proto3" json:"valido_ate,omitempty"`                                      // unix
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RespostaInscricao) Reset() {
	*x = RespostaInscricao{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespostaInscricao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespostaInscricao) ProtoMessage() {}

func (x *RespostaInscricao) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespostaInscricao.ProtoReflect.Descriptor instead.
func (*RespostaInscricao) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{1}
}

func (x *RespostaInscricao) GetAgenteId() string {
	if x != nil {
		return x.AgenteId
	}
	return ""
}

func (x *RespostaInscricao) GetCertificadoDer() []byte {
	if x != nil {
		return x.CertificadoDer
	}
	return nil
}

func (x *RespostaInscricao) GetCaDer() []byte {
	if x != nil {
		return x.CaDer
	}
	return nil
}

func (x *RespostaInscricao) GetChaveAssinaturaPainel() []byte {
	if x != nil {
		return x.ChaveAssinaturaPainel
	}
	return nil
}

func (x *RespostaInscricao) GetValidoAte() int64 {
	if x != nil {
		return x.ValidoAte
	}
	return 0
}

type MsgAgente struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Corpo:
	//
	//	*MsgAgente_Ola
	//	*MsgAgente_Batimento
	//	*MsgAgente_Evento
	//	*MsgAgente_Checkpoint
	//	*MsgAgente_Resultado
	//	*MsgAgente_Esquema
	//	*MsgAgente_Ack
	//	*MsgAgente_Renovacao
	Corpo         isMsgAgente_Corpo `protobuf_oneof:"corpo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAgente) Reset() {
	*x = MsgAgente{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAgente) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAgente) ProtoMessage() {}

func (x *MsgAgente) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAgente.ProtoReflect.Descriptor instead.
func (*MsgAgente) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{2}
}

func (x *MsgAgente) GetCorpo() isMsgAgente_Corpo {
	if x != nil {
		return x.Corpo
	}
	return nil
}

func (x *MsgAgente) GetOla() *Ola {
	if x != nil {
		if x, ok := x.Corpo.(*MsgAgente_Ola); ok {
			return x.Ola
		}
	}
	return nil
}

func (x *MsgAgente) GetBatimento() *Batimento {
	if x != nil {
		if x, ok := x.Corpo.(*MsgAgente_Batimento); ok {
			return x.Batimento
		}
	}
	return nil
}

func (x *MsgAgente) GetEvento() *EventoTarefa {
	if x != nil {
		if x, ok := x.Corpo.(*MsgAgente_Evento); ok {
			return x.Evento
		}
	}
	return nil
}

func (x *MsgAgente) GetCheckpoint() *Checkpoint {
	if x != nil {
		if x, ok := x.Corpo.(*MsgAgente_Checkpoint); ok {
			return x.Checkpoint
		}
	}
	return nil
}

func (x *MsgAgente) GetResultado() *ResultadoTarefa {
	if x != nil {
		if x, ok := x.Corpo.(*MsgAgente_Resultado); ok {
			return x.Resultado
		}
	}
	return nil
}

func (x *MsgAgente) GetEsquema() *RespostaEsquema {
	if x != nil {
		if x, ok := x.Corpo.(*MsgAgente_Esquema); ok {
			return x.Esquema
		}
	}
	return nil
}

func (x *MsgAgente) GetAck() *Confirmacao {
	if x != nil {
		if x, ok := x.Corpo.(*MsgAgente_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *MsgAgente) GetRenovacao() *PedidoRenovacao {
	if x != nil {
		if x, ok := x.Corpo.(*MsgAgente_Renovacao); ok {
			return x.Renovacao
		}
	}
	return nil
}

type isMsgAgente_Corpo interface {
	isMsgAgente_Corpo()
}

type MsgAgente_Ola struct {
	Ola *Ola `protobuf:"bytes,1,opt,name=ola,proto3,oneof"`
}

type MsgAgente_Batimento struct {
	Batimento *Batimento `protobuf:"bytes,2,opt,name=batimento,proto3,oneof"`
}

type MsgAgente_Evento struct {
	Evento *EventoTarefa `protobuf:"bytes,3,opt,name=evento,proto3,oneof"`
}

type MsgAgente_Checkpoint struct {
	Checkpoint *Checkpoint `protobuf:"bytes,4,opt,name=checkpoint,proto3,oneof"`
}

type MsgAgente_Resultado struct {
	Resultado *ResultadoTarefa `protobuf:"bytes,5,opt,name=resultado,proto3,oneof"`
}

type MsgAgente_Esquema struct {
	Esquema *RespostaEsquema `protobuf:"bytes,6,opt,name=esquema,proto3,oneof"`
}

type MsgAgente_Ack struct {
	Ack *Confirmacao `protobuf:"bytes,7,opt,name=ack,proto3,oneof"`
}

type MsgAgente_Renovacao struct {
	Renovacao *PedidoRenovacao `protobuf:"bytes,8,opt,name=renovacao,proto3,oneof"`
}

func (*MsgAgente_Ola) isMsgAgente_Corpo() {}

func (*MsgAgente_Batimento) isMsgAgente_Corpo() {}

func (*MsgAgente_Evento) isMsgAgente_Corpo() {}

func (*MsgAgente_Checkpoint) isMsgAgente_Corpo() {}

func (*MsgAgente_Resultado) isMsgAgente_Corpo() {}

func (*MsgAgente_Esquema) isMsgAgente_Corpo() {}

func (*MsgAgente_Ack) isMsgAgente_Corpo() {}

func (*MsgAgente_Renovacao) isMsgAgente_Corpo() {}

// Ola abre cada conexão: quem é, o que sabe fazer e o que já está em andamento.
type Ola struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgenteId      string                 `protobuf:"bytes,1,opt,name=agente_id,json=agenteId,proto3" json:"agente_id,omitempty"`
	Versao        string                 `protobuf:"bytes,2,opt,name=versao,proto3" json:"versao,omitempty"`
	So            string                 `protobuf:"bytes,3,opt,name=so,proto3" json:"so,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname      string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Capacidades   []string               `protobuf:"bytes,6,rep,name=capacidades,proto3" json:"capacidades,omitempty"`                    // tipos de tarefa liberados na config local
	EmAndamento   []*EstadoTarefa        `protobuf:"bytes,7,rep,name=em_andamento,json=emAndamento,proto3" json:"em_andamento,omitempty"` // para o painel reconciliar depois de uma queda
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ola) Reset() {
	*x = Ola{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ola) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ola) ProtoMessage() {}

func (x *Ola) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ola.ProtoReflect.Descriptor instead.
func (*Ola) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{3}
}

func (x *Ola) GetAgenteId() string {
	if x != nil {
		return x.AgenteId
	}
	return ""
}

func (x *Ola) GetVersao() string {
	if x != nil {
		return x.Versao
	}
	return ""
}

func (x *Ola) GetSo() string {
	if x != nil {
		return x.So
	}
	return ""
}

func (x *Ola) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Ola) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Ola) GetCapacidades() []string {
	if x != nil {
		return x.Capacidades
	}
	return nil
}

func (x *Ola) GetEmAndamento() []*EstadoTarefa {
	if x != nil {
		return x.EmAndamento
	}
	return nil
}

type EstadoTarefa struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TarefaId      string                 `protobuf:"bytes,1,opt,name=tarefa_id,json=tarefaId,proto3" json:"tarefa_id,omitempty"`
	Estado        string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"` // executando | pausada | concluida
	UltimoSeq     int64                  `protobuf:"varint,3,opt,name=ultimo_seq,json=ultimoSeq,proto3" json:"ultimo_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstadoTarefa) Reset() {
	*x = EstadoTarefa{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoTarefa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoTarefa) ProtoMessage() {}

func (x *EstadoTarefa) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoTarefa.ProtoReflect.Descriptor instead.
func (*EstadoTarefa) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{4}
}

func (x *EstadoTarefa) GetTarefaId() string {
	if x != nil {
		return x.TarefaId
	}
	return ""
}

func (x *EstadoTarefa) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *EstadoTarefa) GetUltimoSeq() int64 {
	if x != nil {
		return x.UltimoSeq
	}
	return 0
}

type Batimento struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Em            int64                  `protobuf:"varint,2,opt,name=em,proto3" json:"em,omitempty"` // unix ms
	CpuPct        float64                `protobuf:"fixed64,3,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	MemPct        float64                `protobuf:"fixed64,4,opt,name=mem_pct,json=memPct,proto3" json:"mem_pct,omitempty"`
	TarefasAtivas int32                  `protobuf:"varint,5,opt,name=tarefas_ativas,json=tarefasAtivas,proto3" json:"tarefas_ativas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batimento) Reset() {
	*x = Batimento{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batimento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batimento) ProtoMessage() {}

func (x *Batimento) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batimento.ProtoReflect.Descriptor instead.
func (*Batimento) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{5}
}

func (x *Batimento) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Batimento) GetEm() int64 {
	if x != nil {
		return x.Em
	}
	return 0
}

func (x *Batimento) GetCpuPct() float64 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *Batimento) GetMemPct() float64 {
	if x != nil {
		return x.MemPct
	}
	return 0
}

func (x *Batimento) GetTarefasAtivas() int32 {
	if x != nil {
		return x.TarefasAtivas
	}
	return 0
}

type EventoTarefa struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TarefaId      string                 `protobuf:"bytes,1,opt,name=tarefa_id,json=tarefaId,proto3" json:"tarefa_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Em            int64                  `protobuf:"varint,3,opt,name=em,proto3" json:"em,omitempty"` // unix ms
	Etapa         string                 `protobuf:"bytes,4,opt,name=etapa,proto3" json:"etapa,omitempty"`
	Nivel         EventoTarefa_Nivel     `protobuf:"varint,5,opt,name=nivel,proto3,enum=revoada.agente.v1.EventoTarefa_Nivel" json:"nivel,omitempty"`
	Mensagem      string                 `protobuf:"bytes,6,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Progresso     float64                `protobuf:"fixed64,7,opt,name=progresso,proto3" json:"progresso,omitempty"` // 0..100
	Metricas      map[string]float64     `protobuf:"bytes,8,rep,name=metricas,proto3" json:"metricas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventoTarefa) Reset() {
	*x = EventoTarefa{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventoTarefa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventoTarefa) ProtoMessage() {}

func (x *EventoTarefa) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventoTarefa.ProtoReflect.Descriptor instead.
func (*EventoTarefa) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{6}
}

func (x *EventoTarefa) GetTarefaId() string {
	if x != nil {
		return x.TarefaId
	}
	return ""
}

func (x *EventoTarefa) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EventoTarefa) GetEm() int64 {
	if x != nil {
		return x.Em
	}
	return 0
}

func (x *EventoTarefa) GetEtapa() string {
	if x != nil {
		return x.Etapa
	}
	return ""
}

func (x *EventoTarefa) GetNivel() EventoTarefa_Nivel {
	if x != nil {
		return x.Nivel
	}
	return EventoTarefa_INFO
}

func (x *EventoTarefa) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *EventoTarefa) GetProgresso() float64 {
	if x != nil {
		return x.Progresso
	}
	return 0
}

func (x *EventoTarefa) GetMetricas() map[string]float64 {
	if x != nil {
		return x.Metricas
	}
	return nil
}

type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TarefaId      string                 `protobuf:"bytes,1,opt,name=tarefa_id,json=tarefaId,proto3" json:"tarefa_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Tabela        string                 `protobuf:"bytes,3,opt,name=tabela,proto3" json:"tabela,omitempty"`
	UltimaChave   string                 `protobuf:"bytes,4,opt,name=ultima_chave,json=ultimaChave,proto3" json:"ultima_chave,omitempty"`
	Linhas        int64                  `protobuf:"varint,5,opt,name=linhas,proto3" json:"linhas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{7}
}

func (x *Checkpoint) GetTarefaId() string {
	if x != nil {
		return x.TarefaId
	}
	return ""
}

func (x *Checkpoint) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Checkpoint) GetTabela() string {
	if x != nil {
		return x.Tabela
	}
	return ""
}

func (x *Checkpoint) GetUltimaChave() string {
	if x != nil {
		return x.UltimaChave
	}
	return ""
}

func (x *Checkpoint) GetLinhas() int64 {
	if x != nil {
		return x.Linhas
	}
	return 0
}

type ResultadoTarefa struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TarefaId      string                 `protobuf:"bytes,1,opt,name=tarefa_id,json=tarefaId,proto3" json:"tarefa_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Estado        ResultadoTarefa_Estado `protobuf:"varint,3,opt,name=estado,proto3,enum=revoada.agente.v1.ResultadoTarefa_Estado" json:"estado,omitempty"`
	Erro          string                 `protobuf:"bytes,4,opt,name=erro,proto3" json:"erro,omitempty"`
	Resumo        []byte                 `protobuf:"bytes,5,opt,name=resumo,proto3" json:"resumo,omitempty"` // JSON livre do tipo de tarefa
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoTarefa) Reset() {
	*x = ResultadoTarefa{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoTarefa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoTarefa) ProtoMessage() {}

func (x *ResultadoTarefa) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoTarefa.ProtoReflect.Descriptor instead.
func (*ResultadoTarefa) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{8}
}

func (x *ResultadoTarefa) GetTarefaId() string {
	if x != nil {
		return x.TarefaId
	}
	return ""
}

func (x *ResultadoTarefa) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ResultadoTarefa) GetEstado() ResultadoTarefa_Estado {
	if x != nil {
		return x.Estado
	}
	return ResultadoTarefa_ESTADO_NENHUM
}

func (x *ResultadoTarefa) GetErro() string {
	if x != nil {
		return x.Erro
	}
	return ""
}

func (x *ResultadoTarefa) GetResumo() []byte {
	if x != nil {
		return x.Resumo
	}
	return nil
}

type RespostaEsquema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PedidoId      string                 `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	Esquema       []byte                 `protobuf:"bytes,2,opt,name=esquema,proto3" json:"esquema,omitempty"` // JSON do schema neutro (core/migracao/esquema) — nunca dados
	Erro          string                 `protobuf:"bytes,3,opt,name=erro,proto3" json:"erro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespostaEsquema) Reset() {
	*x = RespostaEsquema{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespostaEsquema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespostaEsquema) ProtoMessage() {}

func (x *RespostaEsquema) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespostaEsquema.ProtoReflect.Descriptor instead.
func (*RespostaEsquema) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{9}
}

func (x *RespostaEsquema) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

func (x *RespostaEsquema) GetEsquema() []byte {
	if x != nil {
		return x.Esquema
	}
	return nil
}

func (x *RespostaEsquema) GetErro() string {
	if x != nil {
		return x.Erro
	}
	return ""
}

type PedidoRenovacao struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrDer        []byte                 `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PedidoRenovacao) Reset() {
	*x = PedidoRenovacao{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PedidoRenovacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedidoRenovacao) ProtoMessage() {}

func (x *PedidoRenovacao) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedidoRenovacao.ProtoReflect.Descriptor instead.
func (*PedidoRenovacao) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{10}
}

func (x *PedidoRenovacao) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type MsgPainel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Corpo:
	//
	//	*MsgPainel_Tarefa
	//	*MsgPainel_Controle
	//	*MsgPainel_PedidoEsquema
	//	*MsgPainel_Ack
	//	*MsgPainel_Renovacao
	Corpo         isMsgPainel_Corpo `protobuf_oneof:"corpo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPainel) Reset() {
	*x = MsgPainel{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPainel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPainel) ProtoMessage() {}

func (x *MsgPainel) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPainel.ProtoReflect.Descriptor instead.
func (*MsgPainel) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{11}
}

func (x *MsgPainel) GetCorpo() isMsgPainel_Corpo {
	if x != nil {
		return x.Corpo
	}
	return nil
}

func (x *MsgPainel) GetTarefa() *Tarefa {
	if x != nil {
		if x, ok := x.Corpo.(*MsgPainel_Tarefa); ok {
			return x.Tarefa
		}
	}
	return nil
}

func (x *MsgPainel) GetControle() *Controle {
	if x != nil {
		if x, ok := x.Corpo.(*MsgPainel_Controle); ok {
			return x.Controle
		}
	}
	return nil
}

func (x *MsgPainel) GetPedidoEsquema() *PedidoEsquema {
	if x != nil {
		if x, ok := x.Corpo.(*MsgPainel_PedidoEsquema); ok {
			return x.PedidoEsquema
		}
	}
	return nil
}

func (x *MsgPainel) GetAck() *Confirmacao {
	if x != nil {
		if x, ok := x.Corpo.(*MsgPainel_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *MsgPainel) GetRenovacao() *RespostaRenovacao {
	if x != nil {
		if x, ok := x.Corpo.(*MsgPainel_Renovacao); ok {
			return x.Renovacao
		}
	}
	return nil
}

type isMsgPainel_Corpo interface {
	isMsgPainel_Corpo()
}

type MsgPainel_Tarefa struct {
	Tarefa *Tarefa `protobuf:"bytes,1,opt,name=tarefa,proto3,oneof"`
}

type MsgPainel_Controle struct {
	Controle *Controle `protobuf:"bytes,2,opt,name=controle,proto3,oneof"`
}

type MsgPainel_PedidoEsquema struct {
	PedidoEsquema *PedidoEsquema `protobuf:"bytes,3,opt,name=pedido_esquema,json=pedidoEsquema,proto3,oneof"`
}

type MsgPainel_Ack struct {
	Ack *Confirmacao `protobuf:"bytes,4,opt,name=ack,proto3,oneof"`
}

type MsgPainel_Renovacao struct {
	Renovacao *RespostaRenovacao `protobuf:"bytes,5,opt,name=renovacao,proto3,oneof"`
}

func (*MsgPainel_Tarefa) isMsgPainel_Corpo() {}

func (*MsgPainel_Controle) isMsgPainel_Corpo() {}

func (*MsgPainel_PedidoEsquema) isMsgPainel_Corpo() {}

func (*MsgPainel_Ack) isMsgPainel_Corpo() {}

func (*MsgPainel_Renovacao) isMsgPainel_Corpo() {}

type Tarefa struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo          string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`                          // diagnostico.eco, migracao.simular, firebird.upgrade…
	Especificacao []byte                 `protobuf:"bytes,3,opt,name=especificacao,proto3" json:"especificacao,omitempty"`        // JSON do tipo
	Credenciais   []*CredencialSelada    `protobuf:"bytes,4,rep,name=credenciais,proto3" json:"credenciais,omitempty"`            // seladas para a chave X25519 DESTE agente
	ExpiraEm      int64                  `protobuf:"varint,5,opt,name=expira_em,json=expiraEm,proto3" json:"expira_em,omitempty"` // unix: depois disso o agente recusa
	Limites       *Limites               `protobuf:"bytes,6,opt,name=limites,proto3" json:"limites,omitempty"`
	CorrelacaoId  string                 `protobuf:"bytes,7,opt,name=correlacao_id,json=correlacaoId,proto3" json:"correlacao_id,omitempty"`
	Assinatura    []byte                 `protobuf:"bytes,8,opt,name=assinatura,proto3" json:"assinatura,omitempty"` // Ed25519 do painel sobre a tarefa com este campo vazio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tarefa) Reset() {
	*x = Tarefa{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tarefa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tarefa) ProtoMessage() {}

func (x *Tarefa) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tarefa.ProtoReflect.Descriptor instead.
func (*Tarefa) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{12}
}

func (x *Tarefa) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tarefa) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Tarefa) GetEspecificacao() []byte {
	if x != nil {
		return x.Especificacao
	}
	return nil
}

func (x *Tarefa) GetCredenciais() []*CredencialSelada {
	if x != nil {
		return x.Credenciais
	}
	return nil
}

func (x *Tarefa) GetExpiraEm() int64 {
	if x != nil {
		return x.ExpiraEm
	}
	return 0
}

func (x *Tarefa) GetLimites() *Limites {
	if x != nil {
		return x.Limites
	}
	return nil
}

func (x *Tarefa) GetCorrelacaoId() string {
	if x != nil {
		return x.CorrelacaoId
	}
	return ""
}

func (x *Tarefa) GetAssinatura() []byte {
	if x != nil {
		return x.Assinatura
	}
	return nil
}

type CredencialSelada struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nome          string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"` // ex.: "origem", "destino"
	Efemera       []byte                 `protobuf:"bytes,2,opt,name=efemera,proto3" json:"efemera,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Cifrado       []byte                 `protobuf:"bytes,4,opt,name=cifrado,proto3" json:"cifrado,omitempty"`
	ExpiraEm      int64                  `protobuf:"varint,5,opt,name=expira_em,json=expiraEm,proto3" json:"expira_em,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredencialSelada) Reset() {
	*x = CredencialSelada{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredencialSelada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredencialSelada) ProtoMessage() {}

func (x *CredencialSelada) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredencialSelada.ProtoReflect.Descriptor instead.
func (*CredencialSelada) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{13}
}

func (x *CredencialSelada) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *CredencialSelada) GetEfemera() []byte {
	if x != nil {
		return x.Efemera
	}
	return nil
}

func (x *CredencialSelada) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *CredencialSelada) GetCifrado() []byte {
	if x != nil {
		return x.Cifrado
	}
	return nil
}

func (x *CredencialSelada) GetExpiraEm() int64 {
	if x != nil {
		return x.ExpiraEm
	}
	return 0
}

type Limites struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       int32                  `protobuf:"varint,1,opt,name=workers,proto3" json:"workers,omitempty"`
	CpuMaxPct     float64                `protobuf:"fixed64,2,opt,name=cpu_max_pct,json=cpuMaxPct,proto3" json:"cpu_max_pct,omitempty"`
	JanelaInicio  string                 `protobuf:"bytes,3,opt,name=janela_inicio,json=janelaInicio,proto3" json:"janela_inicio,omitempty"` // "22:00"
	JanelaFim     string                 `protobuf:"bytes,4,opt,name=janela_fim,json=janelaFim,proto3" json:"janela_fim,omitempty"`          // "06:00"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limites) Reset() {
	*x = Limites{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limites) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limites) ProtoMessage() {}

func (x *Limites) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limites.ProtoReflect.Descriptor instead.
func (*Limites) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{14}
}

func (x *Limites) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *Limites) GetCpuMaxPct() float64 {
	if x != nil {
		return x.CpuMaxPct
	}
	return 0
}

func (x *Limites) GetJanelaInicio() string {
	if x != nil {
		return x.JanelaInicio
	}
	return ""
}

func (x *Limites) GetJanelaFim() string {
	if x != nil {
		return x.JanelaFim
	}
	return ""
}

type Controle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TarefaId      string                 `protobuf:"bytes,1,opt,name=tarefa_id,json=tarefaId,proto3" json:"tarefa_id,omitempty"`
	Acao          Controle_Acao          `protobuf:"varint,2,opt,name=acao,proto3,enum=revoada.agente.v1.Controle_Acao" json:"acao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Controle) Reset() {
	*x = Controle{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Controle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Controle) ProtoMessage() {}

func (x *Controle) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Controle.ProtoReflect.Descriptor instead.
func (*Controle) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{15}
}

func (x *Controle) GetTarefaId() string {
	if x != nil {
		return x.TarefaId
	}
	return ""
}

func (x *Controle) GetAcao() Controle_Acao {
	if x != nil {
		return x.Acao
	}
	return Controle_ACAO_NENHUMA
}

type PedidoEsquema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PedidoId      string                 `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	Motor         string                 `protobuf:"bytes,2,opt,name=motor,proto3" json:"motor,omitempty"` // firebird | postgres
	Endereco      string                 `protobuf:"bytes,3,opt,name=endereco,proto3" json:"endereco,omitempty"`
	Banco         string                 `protobuf:"bytes,4,opt,name=banco,proto3" json:"banco,omitempty"`
	Usuario       string                 `protobuf:"bytes,5,opt,name=usuario,proto3" json:"usuario,omitempty"`
	Credencial    *CredencialSelada      `protobuf:"bytes,6,opt,name=credencial,proto3" json:"credencial,omitempty"`
	Opcoes        map[string]string      `protobuf:"bytes,7,rep,name=opcoes,proto3" json:"opcoes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Assinatura    []byte                 `protobuf:"bytes,8,opt,name=assinatura,proto3" json:"assinatura,omitempty"` // Ed25519 do painel
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PedidoEsquema) Reset() {
	*x = PedidoEsquema{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PedidoEsquema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedidoEsquema) ProtoMessage() {}

func (x *PedidoEsquema) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedidoEsquema.ProtoReflect.Descriptor instead.
func (*PedidoEsquema) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{16}
}

func (x *PedidoEsquema) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

func (x *PedidoEsquema) GetMotor() string {
	if x != nil {
		return x.Motor
	}
	return ""
}

func (x *PedidoEsquema) GetEndereco() string {
	if x != nil {
		return x.Endereco
	}
	return ""
}

func (x *PedidoEsquema) GetBanco() string {
	if x != nil {
		return x.Banco
	}
	return ""
}

func (x *PedidoEsquema) GetUsuario() string {
	if x != nil {
		return x.Usuario
	}
	return ""
}

func (x *PedidoEsquema) GetCredencial() *CredencialSelada {
	if x != nil {
		return x.Credencial
	}
	return nil
}

func (x *PedidoEsquema) GetOpcoes() map[string]string {
	if x != nil {
		return x.Opcoes
	}
	return nil
}

func (x *PedidoEsquema) GetAssinatura() []byte {
	if x != nil {
		return x.Assinatura
	}
	return nil
}

type Confirmacao struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TarefaId      string                 `protobuf:"bytes,1,opt,name=tarefa_id,json=tarefaId,proto3" json:"tarefa_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"` // tudo até este seq foi gravado
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirmacao) Reset() {
	*x = Confirmacao{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirmacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmacao) ProtoMessage() {}

func (x *Confirmacao) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmacao.ProtoReflect.Descriptor instead.
func (*Confirmacao) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{17}
}

func (x *Confirmacao) GetTarefaId() string {
	if x != nil {
		return x.TarefaId
	}
	return ""
}

func (x *Confirmacao) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type RespostaRenovacao struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertificadoDer []byte                 `protobuf:"bytes,1,opt,name=certificado_der,json=certificadoDer,proto3" json:"certificado_der,omitempty"`
	ValidoAte      int64                  `protobuf:"varint,2,opt,name=valido_ate,json=validoAte,proto3" json:"valido_ate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RespostaRenovacao) Reset() {
	*x = RespostaRenovacao{}
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespostaRenovacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespostaRenovacao) ProtoMessage() {}

func (x *RespostaRenovacao) ProtoReflect() protoreflect.Message {
	mi := &file_revoada_agente_v1_agente_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespostaRenovacao.ProtoReflect.Descriptor instead.
func (*RespostaRenovacao) Descriptor() ([]byte, []int) {
	return file_revoada_agente_v1_agente_proto_rawDescGZIP(), []int{18}
}

func (x *RespostaRenovacao) GetCertificadoDer() []byte {
	if x != nil {
		return x.CertificadoDer
	}
	return nil
}

func (x *RespostaRenovacao) GetValidoAte() int64 {
	if x != nil {
		return x.ValidoAte
	}
	return 0
}

var File_revoada_agente_v1_agente_proto protoreflect.FileDescriptor

const file_revoada_agente_v1_agente_proto_rawDesc = "" +
	"\n" +
	"\x1erevoada/agente/v1/agente.proto\x12\x11revoada.agente.v1\"\xb7\x01\n" +
	"\x0fPedidoInscricao\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\x12\x1d\n" +
	"\n" +
	"chave_selo\x18\x03 \x01(\fR\tchaveSelo\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02so\x18\x05 \x01(\tR\x02so\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12\x16\n" +
	"\x06versao\x18\a \x01(\tR\x06versao\"\xc7\x01\n" +
	"\x11RespostaInscricao\x12\x1b\n" +
	"\tagente_id\x18\x01 \x01(\tR\bagenteId\x12'\n" +
	"\x0fcertificado_der\x18\x02 \x01(\fR\x0ecertificadoDer\x12\x15\n" +
	"\x06ca_der\x18\x03 \x01(\fR\x05caDer\x126\n" +
	"\x17chave_assinatura_painel\x18\x04 \x01(\fR\x15chaveAssinaturaPainel\x12\x1d\n" +
	"\n" +
	"valido_ate\x18\x05 \x01(\x03R\tvalidoAte\"\xf6\x03\n" +
	"\tMsgAgente\x12*\n" +
	"\x03ola\x18\x01 \x01(\v2\x16.revoada.agente.v1.OlaH\x00R\x03ola\x12<\n" +
	"\tbatimento\x18\x02 \x01(\v2\x1c.revoada.agente.v1.BatimentoH\x00R\tbatimento\x129\n" +
	"\x06evento\x18\x03 \x01(\v2\x1f.revoada.agente.v1.EventoTarefaH\x00R\x06evento\x12?\n" +
	"\n" +
	"checkpoint\x18\x04 \x01(\v2\x1d.revoada.agente.v1.CheckpointH\x00R\n" +
	"checkpoint\x12B\n" +
	"\tresultado\x18\x05 \x01(\v2\".revoada.agente.v1.ResultadoTarefaH\x00R\tresultado\x12>\n" +
	"\aesquema\x18\x06 \x01(\v2\".revoada.agente.v1.RespostaEsquemaH\x00R\aesquema\x122\n" +
	"\x03ack\x18\a \x01(\v2\x1e.revoada.agente.v1.ConfirmacaoH\x00R\x03ack\x12B\n" +
	"\trenovacao\x18\b \x01(\v2\".revoada.agente.v1.PedidoRenovacaoH\x00R\trenovacaoB\a\n" +
	"\x05corpo\"\xe0\x01\n" +
	"\x03Ola\x12\x1b\n" +
	"\tagente_id\x18\x01 \x01(\tR\bagenteId\x12\x16\n" +
	"\x06versao\x18\x02 \x01(\tR\x06versao\x12\x0e\n" +
	"\x02so\x18\x03 \x01(\tR\x02so\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12 \n" +
	"\vcapacidades\x18\x06 \x03(\tR\vcapacidades\x12B\n" +
	"\fem_andamento\x18\a \x03(\v2\x1f.revoada.agente.v1.EstadoTarefaR\vemAndamento\"b\n" +
	"\fEstadoTarefa\x12\x1b\n" +
	"\ttarefa_id\x18\x01 \x01(\tR\btarefaId\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12\x1d\n" +
	"\n" +
	"ultimo_seq\x18\x03 \x01(\x03R\tultimoSeq\"\x86\x01\n" +
	"\tBatimento\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x0e\n" +
	"\x02em\x18\x02 \x01(\x03R\x02em\x12\x17\n" +
	"\acpu_pct\x18\x03 \x01(\x01R\x06cpuPct\x12\x17\n" +
	"\amem_pct\x18\x04 \x01(\x01R\x06memPct\x12%\n" +
	"\x0etarefas_ativas\x18\x05 \x01(\x05R\rtarefasAtivas\"\x8a\x03\n" +
	"\fEventoTarefa\x12\x1b\n" +
	"\ttarefa_id\x18\x01 \x01(\tR\btarefaId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x0e\n" +
	"\x02em\x18\x03 \x01(\x03R\x02em\x12\x14\n" +
	"\x05etapa\x18\x04 \x01(\tR\x05etapa\x12;\n" +
	"\x05nivel\x18\x05 \x01(\x0e2%.revoada.agente.v1.EventoTarefa.NivelR\x05nivel\x12\x1a\n" +
	"\bmensagem\x18\x06 \x01(\tR\bmensagem\x12\x1c\n" +
	"\tprogresso\x18\a \x01(\x01R\tprogresso\x12I\n" +
	"\bmetricas\x18\b \x03(\v2-.revoada.agente.v1.EventoTarefa.MetricasEntryR\bmetricas\x1a;\n" +
	"\rMetricasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"&\n" +
	"\x05Nivel\x12\b\n" +
	"\x04INFO\x10\x00\x12\t\n" +
	"\x05AVISO\x10\x01\x12\b\n" +
	"\x04ERRO\x10\x02\"\x8e\x01\n" +
	"\n" +
	"Checkpoint\x12\x1b\n" +
	"\ttarefa_id\x18\x01 \x01(\tR\btarefaId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x16\n" +
	"\x06tabela\x18\x03 \x01(\tR\x06tabela\x12!\n" +
	"\fultima_chave\x18\x04 \x01(\tR\vultimaChave\x12\x16\n" +
	"\x06linhas\x18\x05 \x01(\x03R\x06linhas\"\x81\x02\n" +
	"\x0fResultadoTarefa\x12\x1b\n" +
	"\ttarefa_id\x18\x01 \x01(\tR\btarefaId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12A\n" +
	"\x06estado\x18\x03 \x01(\x0e2).revoada.agente.v1.ResultadoTarefa.EstadoR\x06estado\x12\x12\n" +
	"\x04erro\x18\x04 \x01(\tR\x04erro\x12\x16\n" +
	"\x06resumo\x18\x05 \x01(\fR\x06resumo\"P\n" +
	"\x06Estado\x12\x11\n" +
	"\rESTADO_NENHUM\x10\x00\x12\v\n" +
	"\aSUCESSO\x10\x01\x12\t\n" +
	"\x05FALHA\x10\x02\x12\r\n" +
	"\tCANCELADA\x10\x03\x12\f\n" +
	"\bRECUSADA\x10\x04\"\\\n" +
	"\x0fRespostaEsquema\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\tR\bpedidoId\x12\x18\n" +
	"\aesquema\x18\x02 \x01(\fR\aesquema\x12\x12\n" +
	"\x04erro\x18\x03 \x01(\tR\x04erro\"*\n" +
	"\x0fPedidoRenovacao\x12\x17\n" +
	"\acsr_der\x18\x01 \x01(\fR\x06csrDer\"\xc9\x02\n" +
	"\tMsgPainel\x123\n" +
	"\x06tarefa\x18\x01 \x01(\v2\x19.revoada.agente.v1.TarefaH\x00R\x06tarefa\x129\n" +
	"\bcontrole\x18\x02 \x01(\v2\x1b.revoada.agente.v1.ControleH\x00R\bcontrole\x12I\n" +
	"\x0epedido_esquema\x18\x03 \x01(\v2 .revoada.agente.v1.PedidoEsquemaH\x00R\rpedidoEsquema\x122\n" +
	"\x03ack\x18\x04 \x01(\v2\x1e.revoada.agente.v1.ConfirmacaoH\x00R\x03ack\x12D\n" +
	"\trenovacao\x18\x05 \x01(\v2$.revoada.agente.v1.RespostaRenovacaoH\x00R\trenovacaoB\a\n" +
	"\x05corpo\"\xb1\x02\n" +
	"\x06Tarefa\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\x12$\n" +
	"\respecificacao\x18\x03 \x01(\fR\respecificacao\x12E\n" +
	"\vcredenciais\x18\x04 \x03(\v2#.revoada.agente.v1.CredencialSeladaR\vcredenciais\x12\x1b\n" +
	"\texpira_em\x18\x05 \x01(\x03R\bexpiraEm\x124\n" +
	"\alimites\x18\x06 \x01(\v2\x1a.revoada.agente.v1.LimitesR\alimites\x12#\n" +
	"\rcorrelacao_id\x18\a \x01(\tR\fcorrelacaoId\x12\x1e\n" +
	"\n" +
	"assinatura\x18\b \x01(\fR\n" +
	"assinatura\"\x8d\x01\n" +
	"\x10CredencialSelada\x12\x12\n" +
	"\x04nome\x18\x01 \x01(\tR\x04nome\x12\x18\n" +
	"\aefemera\x18\x02 \x01(\fR\aefemera\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x18\n" +
	"\acifrado\x18\x04 \x01(\fR\acifrado\x12\x1b\n" +
	"\texpira_em\x18\x05 \x01(\x03R\bexpiraEm\"\x87\x01\n" +
	"\aLimites\x12\x18\n" +
	"\aworkers\x18\x01 \x01(\x05R\aworkers\x12\x1e\n" +
	"\vcpu_max_pct\x18\x02 \x01(\x01R\tcpuMaxPct\x12#\n" +
	"\rjanela_inicio\x18\x03 \x01(\tR\fjanelaInicio\x12\x1d\n" +
	"\n" +
	"janela_fim\x18\x04 \x01(\tR\tjanelaFim\"\x9e\x01\n" +
	"\bControle\x12\x1b\n" +
	"\ttarefa_id\x18\x01 \x01(\tR\btarefaId\x124\n" +
	"\x04acao\x18\x02 \x01(\x0e2 .revoada.agente.v1.Controle.AcaoR\x04acao\"?\n" +
	"\x04Acao\x12\x10\n" +
	"\fACAO_NENHUMA\x10\x00\x12\n" +
	"\n" +
	"\x06PAUSAR\x10\x01\x12\v\n" +
	"\aRETOMAR\x10\x02\x12\f\n" +
	"\bCANCELAR\x10\x03\"\xf4\x02\n" +
	"\rPedidoEsquema\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\tR\bpedidoId\x12\x14\n" +
	"\x05motor\x18\x02 \x01(\tR\x05motor\x12\x1a\n" +
	"\bendereco\x18\x03 \x01(\tR\bendereco\x12\x14\n" +
	"\x05banco\x18\x04 \x01(\tR\x05banco\x12\x18\n" +
	"\ausuario\x18\x05 \x01(\tR\ausuario\x12C\n" +
	"\n" +
	"credencial\x18\x06 \x01(\v2#.revoada.agente.v1.CredencialSeladaR\n" +
	"credencial\x12D\n" +
	"\x06opcoes\x18\a \x03(\v2,.revoada.agente.v1.PedidoEsquema.OpcoesEntryR\x06opcoes\x12\x1e\n" +
	"\n" +
	"assinatura\x18\b \x01(\fR\n" +
	"assinatura\x1a9\n" +
	"\vOpcoesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\vConfirmacao\x12\x1b\n" +
	"\ttarefa_id\x18\x01 \x01(\tR\btarefaId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\"[\n" +
	"\x11RespostaRenovacao\x12'\n" +
	"\x0fcertificado_der\x18\x01 \x01(\fR\x0ecertificadoDer\x12\x1d\n" +
	"\n" +
	"valido_ate\x18\x02 \x01(\x03R\tvalidoAte2\xaa\x01\n" +
	"\x05Canal\x12U\n" +
	"\tInscrever\x12\".revoada.agente.v1.PedidoInscricao\x1a$.revoada.agente.v1.RespostaInscricao\x12J\n" +
	"\bConectar\x12\x1c.revoada.agente.v1.MsgAgente\x1a\x1c.revoada.agente.v1.MsgPainel(\x010\x01BDZBgithub.com/eduardorarruda/revoada/proto/revoada/agente/v1;agentev1b\x06proto3"

var (
	file_revoada_agente_v1_agente_proto_rawDescOnce sync.Once
	file_revoada_agente_v1_agente_proto_rawDescData []byte
)

func file_revoada_agente_v1_agente_proto_rawDescGZIP() []byte {
	file_revoada_agente_v1_agente_proto_rawDescOnce.Do(func() {
		file_revoada_agente_v1_agente_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_revoada_agente_v1_agente_proto_rawDesc), len(file_revoada_agente_v1_agente_proto_rawDesc)))
	})
	return file_revoada_agente_v1_agente_proto_rawDescData
}

var file_revoada_agente_v1_agente_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_revoada_agente_v1_agente_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_revoada_agente_v1_agente_proto_goTypes = []any{
	(EventoTarefa_Nivel)(0),     // 0: revoada.agente.v1.EventoTarefa.Nivel
	(ResultadoTarefa_Estado)(0), // 1: revoada.agente.v1.ResultadoTarefa.Estado
	(Controle_Acao)(0),          // 2: revoada.agente.v1.Controle.Acao
	(*PedidoInscricao)(nil),     // 3: revoada.agente.v1.PedidoInscricao
	(*RespostaInscricao)(nil),   // 4: revoada.agente.v1.RespostaInscricao
	(*MsgAgente)(nil),           // 5: revoada.agente.v1.MsgAgente
	(*Ola)(nil),                 // 6: revoada.agente.v1.Ola
	(*EstadoTarefa)(nil),        // 7: revoada.agente.v1.EstadoTarefa
	(*Batimento)(nil),           // 8: revoada.agente.v1.Batimento
	(*EventoTarefa)(nil),        // 9: revoada.agente.v1.EventoTarefa
	(*Checkpoint)(nil),          // 10: revoada.agente.v1.Checkpoint
	(*ResultadoTarefa)(nil),     // 11: revoada.agente.v1.ResultadoTarefa
	(*RespostaEsquema)(nil),     // 12: revoada.agente.v1.RespostaEsquema
	(*PedidoRenovacao)(nil),     // 13: revoada.agente.v1.PedidoRenovacao
	(*MsgPainel)(nil),           // 14: revoada.agente.v1.MsgPainel
	(*Tarefa)(nil),              // 15: revoada.agente.v1.Tarefa
	(*CredencialSelada)(nil),    // 16: revoada.agente.v1.CredencialSelada
	(*Limites)(nil),             // 17: revoada.agente.v1.Limites
	(*Controle)(nil),            // 18: revoada.agente.v1.Controle
	(*PedidoEsquema)(nil),       // 19: revoada.agente.v1.PedidoEsquema
	(*Confirmacao)(nil),         // 20: revoada.agente.v1.Confirmacao
	(*RespostaRenovacao)(nil),   // 21: revoada.agente.v1.RespostaRenovacao
	nil,                         // 22: revoada.agente.v1.EventoTarefa.MetricasEntry
	nil,                         // 23: revoada.agente.v1.PedidoEsquema.OpcoesEntry
}
var file_revoada_agente_v1_agente_proto_depIdxs = []int32{
	6,  // 0: revoada.agente.v1.MsgAgente.ola:type_name -> revoada.agente.v1.Ola
	8,  // 1: revoada.agente.v1.MsgAgente.batimento:type_name -> revoada.agente.v1.Batimento
	9,  // 2: revoada.agente.v1.MsgAgente.evento:type_name -> revoada.agente.v1.EventoTarefa
	10, // 3: revoada.agente.v1.MsgAgente.checkpoint:type_name -> revoada.agente.v1.Checkpoint
	11, // 4: revoada.agente.v1.MsgAgente.resultado:type_name -> revoada.agente.v1.ResultadoTarefa
	12, // 5: revoada.agente.v1.MsgAgente.esquema:type_name -> revoada.agente.v1.RespostaEsquema
	20, // 6: revoada.agente.v1.MsgAgente.ack:type_name -> revoada.agente.v1.Confirmacao
	13, // 7: revoada.agente.v1.MsgAgente.renovacao:type_name -> revoada.agente.v1.PedidoRenovacao
	7,  // 8: revoada.agente.v1.Ola.em_andamento:type_name -> revoada.agente.v1.EstadoTarefa
	0,  // 9: revoada.agente.v1.EventoTarefa.nivel:type_name -> revoada.agente.v1.EventoTarefa.Nivel
	22, // 10: revoada.agente.v1.EventoTarefa.metricas:type_name -> revoada.agente.v1.EventoTarefa.MetricasEntry
	1,  // 11: revoada.agente.v1.ResultadoTarefa.estado:type_name -> revoada.agente.v1.ResultadoTarefa.Estado
	15, // 12: revoada.agente.v1.MsgPainel.tarefa:type_name -> revoada.agente.v1.Tarefa
	18, // 13: revoada.agente.v1.MsgPainel.controle:type_name -> revoada.agente.v1.Controle
	19, // 14: revoada.agente.v1.MsgPainel.pedido_esquema:type_name -> revoada.agente.v1.PedidoEsquema
	20, // 15: revoada.agente.v1.MsgPainel.ack:type_name -> revoada.agente.v1.Confirmacao
	21, // 16: revoada.agente.v1.MsgPainel.renovacao:type_name -> revoada.agente.v1.RespostaRenovacao
	16, // 17: revoada.agente.v1.Tarefa.credenciais:type_name -> revoada.agente.v1.CredencialSelada
	17, // 18: revoada.agente.v1.Tarefa.limites:type_name -> revoada.agente.v1.Limites
	2,  // 19: revoada.agente.v1.Controle.acao:type_name -> revoada.agente.v1.Controle.Acao
	16, // 20: revoada.agente.v1.PedidoEsquema.credencial:type_name -> revoada.agente.v1.CredencialSelada
	23, // 21: revoada.agente.v1.PedidoEsquema.opcoes:type_name -> revoada.agente.v1.PedidoEsquema.OpcoesEntry
	3,  // 22: revoada.agente.v1.Canal.Inscrever:input_type -> revoada.agente.v1.PedidoInscricao
	5,  // 23: revoada.agente.v1.Canal.Conectar:input_type -> revoada.agente.v1.MsgAgente
	4,  // 24: revoada.agente.v1.Canal.Inscrever:output_type -> revoada.agente.v1.RespostaInscricao
	14, // 25: revoada.agente.v1.Canal.Conectar:output_type -> revoada.agente.v1.MsgPainel
	24, // [24:26] is the sub-list for method output_type
	22, // [22:24] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_revoada_agente_v1_agente_proto_init() }
func file_revoada_agente_v1_agente_proto_init() {
	if File_revoada_agente_v1_agente_proto != nil {
		return
	}
	file_revoada_agente_v1_agente_proto_msgTypes[2].OneofWrappers = []any{
		(*MsgAgente_Ola)(nil),
		(*MsgAgente_Batimento)(nil),
		(*MsgAgente_Evento)(nil),
		(*MsgAgente_Checkpoint)(nil),
		(*MsgAgente_Resultado)(nil),
		(*MsgAgente_Esquema)(nil),
		(*MsgAgente_Ack)(nil),
		(*MsgAgente_Renovacao)(nil),
	}
	file_revoada_agente_v1_agente_proto_msgTypes[11].OneofWrappers = []any{
		(*MsgPainel_Tarefa)(nil),
		(*MsgPainel_Controle)(nil),
		(*MsgPainel_PedidoEsquema)(nil),
		(*MsgPainel_Ack)(nil),
		(*MsgPainel_Renovacao)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_revoada_agente_v1_agente_proto_rawDesc), len(file_revoada_agente_v1_agente_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_revoada_agente_v1_agente_proto_goTypes,
		DependencyIndexes: file_revoada_agente_v1_agente_proto_depIdxs,
		EnumInfos:         file_revoada_agente_v1_agente_proto_enumTypes,
		MessageInfos:      file_revoada_agente_v1_agente_proto_msgTypes,
	}.Build()
	File_revoada_agente_v1_agente_proto = out.File
	file_revoada_agente_v1_agente_proto_goTypes = nil
	file_revoada_agente_v1_agente_proto_depIdxs = nil
}
